- BLACS/SRC/blacs_get_.c
- BLACS/SRC/cgamn2d_.c
- BLACS/SRC/cgamx2d_.c
- BLACS/SRC/dgamn2d_.c
- BLACS/SRC/dgamx2d_.c
- BLACS/SRC/igamn2d_.c
- BLACS/SRC/igamx2d_.c
- BLACS/SRC/sgamn2d_.c
- BLACS/SRC/sgamx2d_.c
- BLACS/SRC/zgamn2d_.c
- BLACS/SRC/zgamx2d_.c
MPI_Attr_get and MPI_Type_struct were deprecated in MPI-2 and removed
in MPI-3.  Open MPI 4.0 is the first widely used implementation that
actually removed these symbols.  This change breaks compatibility with
MPI-1 implementations.
> MPI-3+ updates required by Open MPI 4

- SRC/CMakeLists.txt
- SRC/Makefile
This adds the missing functions to the library.
However, it seems no function is calling these functions.
> maint: added p*trcon to library fixes #11

- CMAKE/FortranMangling.cmake
Fix CMake invocation that breaks some versions of CMake as described in Kitware's regression:
https://gitlab.kitware.com/cmake/cmake/issues/18817
Fixes #9
> Change Fortran mangling test in CMake

- PBLAS/SRC/pdamax_.c
- PBLAS/SRC/pdasum_.c
- PBLAS/SRC/pdger_.c
- PBLAS/SRC/pdnrm2_.c
- PBLAS/SRC/pdscal_.c
- PBLAS/SRC/psamax_.c
- PBLAS/SRC/psasum_.c
- PBLAS/SRC/psger_.c
- PBLAS/SRC/psnrm2_.c
- PBLAS/SRC/psscal_.c
An integer overflow occurs and causes segmentation fault
when 2D row/col index is linearized using 32-bit integers.
PBLAS Mptr() macro should be used instead.
This fix only fixes address calculations with row, column, and leading
dimension. There might be other places where an overflow occurs but
they may not matter for practical purposes because they would require
very large matrices or very long vectors within a single process.
> Use pointer macro to prevent integer oveflow

- CMakeLists.txt
For checking whether the Intel Fortran compiler is being used, employ the CMake variable `CMAKE_Fortran_COMPILER_ID` rather than the original `CMAKE_Fortran_COMPILER`.
The original code did not support using the ***mpifort*** compiler wrapper with (for instance) ***gfortran***, because ***mpifort*** matched the pattern `"ifort"`, which resulted in addition of compiler flags not supported by ***gfortran***.
On the contrary, for Intel compiler, `CMAKE_Fortran_COMPILER_ID` is set to `"Intel"`, regardless whether it is used directly or inside a MPI wrapper. Similarly, it returns `"GNU"` for ***gfortran***, whether used directly or via ***mpifort***.
Resolve #18
> Use CMAKE_Fortran_COMPILER_ID instead of CMAKE_Fortran_COMPILER

- BLACS/CMakeLists.txt
- CMakeLists.txt
- PBLAS/CMakeLists.txt
- REDIST/CMakeLists.txt
See #29  for some initial discussion.
By default, tests are build as was the case before this PR.
By using `cmake -DSCALAPACK_BUILD_TESTS=OFF`, users can turn off building tests and save on build time.
The same was possible by specifying a target (`make scalapack`), but giving a cmake option is good practice I believe.
Note that PBLAS/TIMING is also considered a "test" and is thus not build when `SCALAPACK_BUILD_TESTS` is turned off by the user.
I also deleted some spaces at the end of several lines (automatically, many editors like vim do this).
> New option: SCALAPACK_BUILD_TESTS

- SRC/pdtrord.f
- SRC/pstrord.f
- SRC/pstrsen.f
See #32 for details
Before this fix I had a lot of error messages about illegal value in P?TRORD in x?hseqr tests on some systems. 
```
{    1,    0}:  On entry to PDTRORD parameter number **** had an illegal value
{    0,    0}:  On entry to PDTRORD parameter number **** had an illegal value
{    1,    1}:  On entry to PDTRORD parameter number **** had an illegal value
{    0,    1}:  On entry to PDTRORD parameter number **** had an illegal value
``` 
And interesting detail is that xdhseqr test prints such messages and then finishes with PASSED check, but xshseqr test prints messages endlessly and never finishes.
After this fix these messages are gone and x?hseqr tests works normally on all systems. 
Also I found same error in PSTRSEN and fixed it.
> Fix info distribution in P?TRORD and PSTRSEN

- BLACS/SRC/blacs_exit_.c
- BLACS/SRC/blacs_pinfo_.c
This should enable ScaLAPACK/BLACS to be exited and restarted
at will without memory leaks or problems.
When called with blacs_exit(true), the comm_world will be
retained and MPI_Finalized won't be called.
Only when blacs_exit(false) is called will the BI_COMM_WORLD
be de-allocated. So one should expect a memory leak of
an integer if the hosting application calls MPI_Finalize.
For instance the `blacs_exit` test example can now be extended to this:
```fortran
PROGRAM HELLO
*     -- BLACS example code --
*     Written by Clint Whaley 7/26/94
*     Performs a simple check-in type hello world
*     ..
*     .. External Functions ..
INTEGER BLACS_PNUM
EXTERNAL BLACS_PNUM
*     ..
*     .. Variable Declaration ..
INTEGER CONTXT, IAM, NPROCS, NPROW, NPCOL, MYPROW, MYPCOL
INTEGER ICALLER, I, J, …
```
> enh: no memory leaks for blacs_exit and allow re-call

- CMakeLists.txt
- README
Set the ScaLAPACK project version in a single place, at the project
command in CMakeLists.txt.
This defines SCALAPACK_VERSION, from which cmake derives
SCALAPACK_VERSION_MAJOR, SCALAPACK_VERSION_MINOR, SCALAPACK_VERSION_PATCH
Use SCALAPACK_VERSION as the shared library VERSION (defining the
shared library file as libscalapack.so.2.2.1)
and use SCALAPACK_VERSION_MAJOR.SCALAPACK_VERSION_MINOR as the shared
library SOVERSION (defining the soname as libscalapack.so.2.2)
That is, assume that the ABI updates with each MINOR release and
reflect that in the soname.
An API update (and therefore an ABI update) would be expected with any
MAJOR release.
No ABI update should occur with a PATCH release.
Closes: #46
> set project version and shared library soname

- BLACS/Makefile
- Makefile
In order for `make -j` to work correctly, the BLACS library should be built before the other libraries. This can be achieved with an explicit dependency.
Also, the child make processes must be launched with `$(MAKE)` so that the `-j` option is propagated correctly.
> Fix parallel builds with GNU make

- PBLAS/SRC/PTZBLAS/cvvdotc.f
- PBLAS/SRC/PTZBLAS/cvvdotu.f
- PBLAS/SRC/PTZBLAS/zvvdotc.f
- PBLAS/SRC/PTZBLAS/zvvdotu.f
- SRC/clanv2.f
- SRC/pcdttrf.f
- SRC/pchetd2.f
- SRC/pclarfg.f
- SRC/pclattrs.f
- SRC/pclauu2.f
- SRC/pdtrord.f
- SRC/pstrord.f
- SRC/pstrsen.f
- SRC/pzdttrf.f
- SRC/pzhetd2.f
- SRC/pzlarfg.f
- SRC/pzlattrs.f
- SRC/pzlauu2.f
- SRC/pzpotf2.f
- SRC/zlanv2.f
- TOOLS/LAPACK/claghe.f
- TOOLS/LAPACK/clagsy.f
- TOOLS/LAPACK/zlaghe.f
- TOOLS/LAPACK/zlagsy.f
- TOOLS/ccdotc.f
- TOOLS/ccdotu.f
- TOOLS/zzdotc.f
- TOOLS/zzdotu.f
You may want to add these changes, intended to avoid issues in macOS due to special calling convention. We have had these changes in PETSc's `--download-scalapack` for two years now, but it is better if they can be added upstream.
> Fixes for macOS portability

- BLACS/INSTALL/CMakeLists.txt
- CMakeLists.txt
> Set CMAKE_POSITION_INDEPENDENT_CODE if need be

- CMakeLists.txt
The CMake operator `VERSION_GREATER_EQUAL` was introduced in CMake 3.7, and therefore we should require this version in ScaLAPACK.
> Update CMake requirements

- SRC/CMakeLists.txt
- SRC/Makefile
Source files were available, but not compiled. Fixes issue #88
> Added PxTRRFS to SRC/Makefile and SRC/CMakeLists.txt

- BLACS/TESTING/blacstest.f
This PR fixes warnings from gcc about some Fortran 2018 deleted feature in `blacstest.f` reported as part of #92.
Background: DO with shared termination was declared obsolescent in Fortran 90 [cf. https://fortranwiki.org/fortran/show/Modernizing+Old+Fortran ] . Instead `DO -> END DO` syntax should be used.
#
> Fix gcc warnings about Fortran 2018 deleted features

- REDIST/SRC/pcgemr.c
- REDIST/SRC/pcgemr2.c
- REDIST/SRC/pctrmr.c
- REDIST/SRC/pctrmr2.c
- REDIST/SRC/pdgemr.c
- REDIST/SRC/pdgemr2.c
- REDIST/SRC/pdtrmr.c
- REDIST/SRC/pdtrmr2.c
- REDIST/SRC/pgemraux.c
- REDIST/SRC/pigemr.c
- REDIST/SRC/pigemr2.c
- REDIST/SRC/pitrmr.c
- REDIST/SRC/pitrmr2.c
- REDIST/SRC/psgemr.c
- REDIST/SRC/psgemr2.c
- REDIST/SRC/pstrmr.c
- REDIST/SRC/pstrmr2.c
- REDIST/SRC/pzgemr.c
- REDIST/SRC/pzgemr2.c
- REDIST/SRC/pztrmr.c
- REDIST/SRC/pztrmr2.c
In C, the type of the number of bytes passed to `malloc` *is* of type `size_t`.
The current code ties that number of bytes to the general "Index type" (`Int`) which is defined at compile time and does fail on 32-bits systems setting `Int` as 64-bits if the number exceeds the 32-bit range.
Additionally, this artificially limits 64-bit-element aux matrices to 2GB instead of 16GB with 32-bits signed indices. This is a limit I have reached.
Changing the type back to `size_t` fixes all of that.
> Use `size_t` in `mr2d_malloc` instead of index-bound `Int`

- SRC/pclacon.f
- SRC/pdlacon.f
- SRC/pslacon.f
- SRC/pzlacon.f
Turned out that the problem was with uninitialized output param `EST` in `p?lacon`. Simply `EST = ZERO` solves the problem
Closes #121
> Fix uninitialized EST in Placon

- .github/workflows/make.yml
- SRC/Makefile
The `CFLAGS` in this line should be `CCFLAGS`, as used everywhere else. See discussion in #17.
`CFLAGS` is more standard, but since online instructions and scripts refer to `CCFLAGS`, it makes sense to keep that.
Also in the CI, disable `make -j`, which is buggy. See #54.
> make: fix CCFLAGS. Resolves #17.

- REDIST/SRC/pcgemr.c
- REDIST/SRC/pcgemr2.c
- REDIST/SRC/pctrmr.c
- REDIST/SRC/pctrmr2.c
- REDIST/SRC/pdgemr.c
- REDIST/SRC/pdgemr2.c
- REDIST/SRC/pdtrmr.c
- REDIST/SRC/pdtrmr2.c
- REDIST/SRC/pgemraux.c
- REDIST/SRC/pigemr.c
- REDIST/SRC/pigemr2.c
- REDIST/SRC/pitrmr.c
- REDIST/SRC/pitrmr2.c
- REDIST/SRC/psgemr.c
- REDIST/SRC/psgemr2.c
- REDIST/SRC/pstrmr.c
- REDIST/SRC/pstrmr2.c
- REDIST/SRC/pzgemr.c
- REDIST/SRC/pzgemr2.c
- REDIST/SRC/pztrmr.c
- REDIST/SRC/pztrmr2.c
- SRC/getpbbuf.c
- SRC/pbchkvect.c
- SRC/pcrot.c
- SRC/pzrot.c
- TOOLS/SL_gridreshape.c
- TOOLS/reshape.c
This PR fixes various compiler errors shown by gcc 15, relating to function signatures that do not match their argument lists. This required a modest amount of re-ordering and adding in a few `#include <stddef.h>` if the relevant types weren't available. A reasonable attempt was made to respect surrounding style, but I'm sure there will be a mistake.  
Should fix https://github.com/Reference-ScaLAPACK/scalapack/issues/129
> Fix function declaration argument error

- CMakeLists.txt
Hi,
I think there is no harm in setting the C standard to the version the code actually conforms to at the moment.
Though I'd agree that updating the code to conform to C23 should be the long term goal.
Addresses #129.
Cheers,
Nuno
> Set C std to C17 to avoid errors with gcc 15

- .github/workflows/make.yml
It looks like the Makefile CI is failing on [some prs](https://github.com/Reference-ScaLAPACK/scalapack/actions/runs/16199584594/job/45734943013?pr=140) due to a missing lapack install, this is copied from the cmake github action install of lapack, which I assume is sufficient.
> Add installation of lapack and blas to Makefile github action runner

- BLACS/SRC/dgamn2d_.c
- BLACS/SRC/dgamx2d_.c
- BLACS/SRC/dgsum2d_.c
- BLACS/SRC/igamn2d_.c
- BLACS/SRC/igamx2d_.c
- BLACS/SRC/igsum2d_.c
- BLACS/SRC/sgamn2d_.c
- BLACS/SRC/sgamx2d_.c
- BLACS/SRC/sgsum2d_.c
- REDIST/SRC/pcgemr.c
- REDIST/SRC/pctrmr.c
- REDIST/SRC/pdgemr.c
- REDIST/SRC/pdtrmr.c
- REDIST/SRC/pigemr.c
- REDIST/SRC/pitrmr.c
- REDIST/SRC/psgemr.c
- REDIST/SRC/pstrmr.c
- REDIST/SRC/pzgemr.c
- REDIST/SRC/pztrmr.c
- SRC/pcrot.c
- SRC/pzrot.c
Compiling with gcc 15 on `eb358820a32db60100a042ce9bc8b99a88e41d1e` I have errors due to miscasting of `bp->Buff` which is `char*` to `Int*` in `BI_ivmcopy` and `BI_imvcopy` and various other of these copy methods. These were introduced in https://github.com/Reference-ScaLAPACK/scalapack/pull/137 which exposed that the buffer class being used with these methods is a char*, whereas these all assume matching type buffers. 
This fixes the issue with a cast, but is not attempting to understand if these buffers are actually appropriately sized, which is a much bigger question. This will restore the previous behaviour, (by masking it with the cast), but is not endorsing the handling of these buffers in any way.
Example error message:
```
[  3%] Building C object …
```
> Fix incompatible pointer type
